# Generated by Django 3.2 on 2021-04-22 21:49

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(blank=True, max_length=30)),
                ('office', models.CharField(blank=True, max_length=30)),
                ('allergy', accounts.models.MultiSelectField(choices=[('SHELL', '갑각류 알레르기'), ('NUT', '견과 알레르기'), ('EGG', '달걀 알레르기'), ('PNUT', '땅콩 알레르기'), ('WHEAT', '밀 알레르기'), ('FISH', '생선 알레르기'), ('MILK', '우유 알레르기'), ('CLAM', '조개 알레르기'), ('BEAN', '콩 알레르기')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
