# Generated by Django 3.2 on 2021-04-24 01:45

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210424_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_latlng',
            field=accounts.models.LatLngField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office_latlng',
            field=accounts.models.LatLngField(blank=True, max_length=50),
        ),
    ]
